### ISSUE TITLE
Wrong initial route

### ISSUE THREAD

**Issue by utherpally** [David-OConnor/seed-homepage#6]
I want to share a link about Routing section but it show content of the homepage (`https://seed-rs.org/`) with active Quick Start section by default.
My step: Open Chrome -> Paste `https://seed-rs.org/guide/7` in address bar and enter.

**Comment by David-OConnor** [comment]
Leaning bug in Seed itself.

**Comment by David-OConnor** [comment]
https://github.com/David-OConnor/seed/issues/224

Caused by me not understanding an API change that was made. Fixed and live.

**Comment by David-OConnor** [comment]
New routing url format for the guide: `https://seed-rs.org/guide/routing`
