### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed-homepage#8]
https://seed-rs.netlify.com/

https://github.com/MartinKavik/seed-rs.org

**Comment by David-OConnor** [comment]
I like it. How do we make this happen?

I like both the new style, and the lack of reliance on `pandoc`.

edit: I probably just need to point the domain to your hosting.

**Comment by MartinKavik** [comment]
> I probably just need to point the domain to your hosting.

You can try it, but I don't know if it's the proper solution.

I've added you as the collaborator to MartinKavik/seed-rs.org.

I'm thinking about creating a new GitHub org, so you have full access to all my Seed-related projects, CI pipelines, etc.

Let's continue through mails, I think it's not interesting for users. We can report back the results later.
